# Generated by Django 4.2.4 on 2023-08-27 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
