# Generated by Django 4.2.4 on 2023-08-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image5',
        ),
    ]
