# Generated by Django 4.2.4 on 2023-08-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_products_image4_remove_products_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
    ]
