# Generated by Django 4.2.4 on 2023-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_products_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
    ]
